version: "3.7"

services:
  lsp-java:
    ports:
      - "1044:1044"
    image: justin2004/lsp-java
    build: .
    #    environment:
    #      DISPLAY: ${DISPLAY}
    volumes:
      - type: bind
        source: /mnt/b
        target: /mnt/b
        read_only: false
    command: bash -c 'cd /root/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository &&  while true ; do socat -d tcp-listen:1044,reuseaddr exec:"java  -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.level=ALL -noverify -Xmx1G -jar ./plugins/org.eclipse.equinox.launcher_1.5.700.v20200107-1357.jar  -configuration ./config_linux -data /root/data" ; done'

    # .vimrc
#let g:lsc_server_commands = {  'java' : {    'name': 'java-langserver',    'command': 'myjavalangserver.sh'} }
#let g:lsc_auto_map = v:true
#set completeopt=menu,menuone,noinsert,noselect
#

    # bin
#myjavalangserver:
#socat - TCP:127.0.0.1:1044
